name: "👨‍💻 Technical improvement"
description: Create a new ticket for a new feature request
title: "👨‍💻 <title>"
labels: [
  "👨‍💻 Tech"
]
body:
  - type: textarea
    id: utility
    attributes:
      label: "Utility"
      description: A clear and concise description of what the tech is.
    validations:
      required: false
  - type: textarea
    id: links
    attributes:
      label: "Links"
      description: Add any other context or links about the tech request here.
    validations:
      required: true
